// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dipper/app/server/service/internal/biz"
	"dipper/app/server/service/internal/conf"
	"dipper/app/server/service/internal/data"
	"dipper/app/server/service/internal/server"
	"dipper/app/server/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	dataData, cleanup, err := data.NewData(client, logger)
	if err != nil {
		return nil, nil, err
	}
	hostRepo := data.NewHostRepo(dataData, logger)
	hostUseCase := biz.NewHostUseCase(confServer, hostRepo, logger)
	blacklistRepo := data.NewBlacklistRepo(dataData, logger)
	blacklistUseCase := biz.NewBlacklistUseCase(blacklistRepo, logger)
	serverService := service.NewServerService(hostUseCase, blacklistUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, tracerProvider, serverService)
	grpcServer := server.NewGRPCServer(confServer, logger, tracerProvider, serverService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
