// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlacklistsColumns holds the columns for the "blacklists" table.
	BlacklistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "is_deleted", Type: field.TypeUint8, Default: 0},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"sqlite3": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"sqlite3": "datetime"}},
	}
	// BlacklistsTable holds the schema information for the "blacklists" table.
	BlacklistsTable = &schema.Table{
		Name:       "blacklists",
		Columns:    BlacklistsColumns,
		PrimaryKey: []*schema.Column{BlacklistsColumns[0]},
	}
	// HostsColumns holds the columns for the "hosts" table.
	HostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "manager", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "verify_code", Type: field.TypeString},
		{Name: "cert_num", Type: field.TypeInt64, Default: 0},
		{Name: "is_deleted", Type: field.TypeUint8, Default: 0},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"sqlite3": "datetime"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"sqlite3": "datetime"}},
	}
	// HostsTable holds the schema information for the "hosts" table.
	HostsTable = &schema.Table{
		Name:       "hosts",
		Columns:    HostsColumns,
		PrimaryKey: []*schema.Column{HostsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlacklistsTable,
		HostsTable,
	}
)

func init() {
}
