// Code generated by entc, DO NOT EDIT.

package host

import (
	"time"
)

const (
	// Label holds the string label denoting the host type in the database.
	Label = "host"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldManager holds the string denoting the manager field in the database.
	FieldManager = "manager"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldVerifyCode holds the string denoting the verify_code field in the database.
	FieldVerifyCode = "verify_code"
	// FieldCertNum holds the string denoting the cert_num field in the database.
	FieldCertNum = "cert_num"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the host in the database.
	Table = "hosts"
)

// Columns holds all SQL columns for host fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldManager,
	FieldPhone,
	FieldVerifyCode,
	FieldCertNum,
	FieldIsDeleted,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCertNum holds the default value on creation for the "cert_num" field.
	DefaultCertNum int64
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted uint8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultCreatedAt holds the default value on update for the "created_at" field.
	UpdateDefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
