// Code generated by entc, DO NOT EDIT.

package ent

import (
	"dipper/app/server/service/internal/data/ent/blacklist"
	"dipper/app/server/service/internal/data/ent/host"
	"dipper/app/server/service/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blacklistFields := schema.Blacklist{}.Fields()
	_ = blacklistFields
	// blacklistDescIsDeleted is the schema descriptor for is_deleted field.
	blacklistDescIsDeleted := blacklistFields[2].Descriptor()
	// blacklist.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	blacklist.DefaultIsDeleted = blacklistDescIsDeleted.Default.(uint8)
	// blacklistDescCreatedAt is the schema descriptor for created_at field.
	blacklistDescCreatedAt := blacklistFields[3].Descriptor()
	// blacklist.DefaultCreatedAt holds the default value on creation for the created_at field.
	blacklist.DefaultCreatedAt = blacklistDescCreatedAt.Default.(func() time.Time)
	// blacklist.UpdateDefaultCreatedAt holds the default value on update for the created_at field.
	blacklist.UpdateDefaultCreatedAt = blacklistDescCreatedAt.UpdateDefault.(func() time.Time)
	// blacklistDescUpdatedAt is the schema descriptor for updated_at field.
	blacklistDescUpdatedAt := blacklistFields[4].Descriptor()
	// blacklist.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blacklist.DefaultUpdatedAt = blacklistDescUpdatedAt.Default.(func() time.Time)
	// blacklist.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blacklist.UpdateDefaultUpdatedAt = blacklistDescUpdatedAt.UpdateDefault.(func() time.Time)
	hostFields := schema.Host{}.Fields()
	_ = hostFields
	// hostDescCertNum is the schema descriptor for cert_num field.
	hostDescCertNum := hostFields[5].Descriptor()
	// host.DefaultCertNum holds the default value on creation for the cert_num field.
	host.DefaultCertNum = hostDescCertNum.Default.(int64)
	// hostDescIsDeleted is the schema descriptor for is_deleted field.
	hostDescIsDeleted := hostFields[6].Descriptor()
	// host.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	host.DefaultIsDeleted = hostDescIsDeleted.Default.(uint8)
	// hostDescCreatedAt is the schema descriptor for created_at field.
	hostDescCreatedAt := hostFields[7].Descriptor()
	// host.DefaultCreatedAt holds the default value on creation for the created_at field.
	host.DefaultCreatedAt = hostDescCreatedAt.Default.(func() time.Time)
	// host.UpdateDefaultCreatedAt holds the default value on update for the created_at field.
	host.UpdateDefaultCreatedAt = hostDescCreatedAt.UpdateDefault.(func() time.Time)
	// hostDescUpdatedAt is the schema descriptor for updated_at field.
	hostDescUpdatedAt := hostFields[8].Descriptor()
	// host.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	host.DefaultUpdatedAt = hostDescUpdatedAt.Default.(func() time.Time)
	// host.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	host.UpdateDefaultUpdatedAt = hostDescUpdatedAt.UpdateDefault.(func() time.Time)
}
