// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blacklist is the predicate function for blacklist builders.
type Blacklist func(*sql.Selector)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)
