// Code generated by entc, DO NOT EDIT.

package ent

import (
	"dipper/app/client/service/internal/data/ent/cfg"
	"dipper/app/client/service/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cfgFields := schema.Cfg{}.Fields()
	_ = cfgFields
	// cfgDescIsDeleted is the schema descriptor for is_deleted field.
	cfgDescIsDeleted := cfgFields[2].Descriptor()
	// cfg.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	cfg.DefaultIsDeleted = cfgDescIsDeleted.Default.(uint8)
	// cfgDescCreatedAt is the schema descriptor for created_at field.
	cfgDescCreatedAt := cfgFields[3].Descriptor()
	// cfg.DefaultCreatedAt holds the default value on creation for the created_at field.
	cfg.DefaultCreatedAt = cfgDescCreatedAt.Default.(func() time.Time)
	// cfg.UpdateDefaultCreatedAt holds the default value on update for the created_at field.
	cfg.UpdateDefaultCreatedAt = cfgDescCreatedAt.UpdateDefault.(func() time.Time)
	// cfgDescUpdatedAt is the schema descriptor for updated_at field.
	cfgDescUpdatedAt := cfgFields[4].Descriptor()
	// cfg.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cfg.DefaultUpdatedAt = cfgDescUpdatedAt.Default.(func() time.Time)
	// cfg.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cfg.UpdateDefaultUpdatedAt = cfgDescUpdatedAt.UpdateDefault.(func() time.Time)
}
