// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/server/service/v1/host.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Manager    string `protobuf:"bytes,3,opt,name=manager,proto3" json:"manager,omitempty"`
	Phone      string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	VerifyCode string `protobuf:"bytes,5,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{0}
}

func (x *HostInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HostInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostInfo) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *HostInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *HostInfo) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type CreateHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Manager    string `protobuf:"bytes,2,opt,name=manager,proto3" json:"manager,omitempty"`
	Phone      string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	VerifyCode string `protobuf:"bytes,4,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
}

func (x *CreateHostReq) Reset() {
	*x = CreateHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostReq) ProtoMessage() {}

func (x *CreateHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostReq.ProtoReflect.Descriptor instead.
func (*CreateHostReq) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHostReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHostReq) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *CreateHostReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateHostReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type CreateHostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *HostInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateHostReply) Reset() {
	*x = CreateHostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostReply) ProtoMessage() {}

func (x *CreateHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostReply.ProtoReflect.Descriptor instead.
func (*CreateHostReply) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHostReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateHostReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateHostReply) GetData() *HostInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHostReq) Reset() {
	*x = ListHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostReq) ProtoMessage() {}

func (x *ListHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostReq.ProtoReflect.Descriptor instead.
func (*ListHostReq) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{3}
}

type ListHostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*HostInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListHostReply) Reset() {
	*x = ListHostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostReply) ProtoMessage() {}

func (x *ListHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostReply.ProtoReflect.Descriptor instead.
func (*ListHostReply) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{4}
}

func (x *ListHostReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListHostReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListHostReply) GetData() []*HostInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetHostByVerifyCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifyCode string `protobuf:"bytes,1,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
}

func (x *GetHostByVerifyCodeReq) Reset() {
	*x = GetHostByVerifyCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostByVerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostByVerifyCodeReq) ProtoMessage() {}

func (x *GetHostByVerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostByVerifyCodeReq.ProtoReflect.Descriptor instead.
func (*GetHostByVerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{5}
}

func (x *GetHostByVerifyCodeReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type GetHostByVerifyCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host *HostInfo `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *GetHostByVerifyCodeReply) Reset() {
	*x = GetHostByVerifyCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostByVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostByVerifyCodeReply) ProtoMessage() {}

func (x *GetHostByVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostByVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*GetHostByVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{6}
}

func (x *GetHostByVerifyCodeReply) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

type AuthHostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifyCode string `protobuf:"bytes,1,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
}

func (x *AuthHostReq) Reset() {
	*x = AuthHostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthHostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthHostReq) ProtoMessage() {}

func (x *AuthHostReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthHostReq.ProtoReflect.Descriptor instead.
func (*AuthHostReq) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{7}
}

func (x *AuthHostReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type AuthHostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert string `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AuthHostReply) Reset() {
	*x = AuthHostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_service_v1_host_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthHostReply) ProtoMessage() {}

func (x *AuthHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_service_v1_host_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthHostReply.ProtoReflect.Descriptor instead.
func (*AuthHostReply) Descriptor() ([]byte, []int) {
	return file_api_server_service_v1_host_proto_rawDescGZIP(), []int{8}
}

func (x *AuthHostReply) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *AuthHostReply) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_api_server_service_v1_host_proto protoreflect.FileDescriptor

var file_api_server_service_v1_host_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x73, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x6c, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x6a, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x38, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x42, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x4f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x22, 0x2d, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x35, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x65, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0xc1, 0x03, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x78, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x24, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x61, 0x64, 0x64, 0x12, 0x72, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x61, 0x6c, 0x6c, 0x12, 0x75, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x73, 0x74, 0x42, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x48, 0x6f, 0x73, 0x74,
	0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3a, 0x0a, 0x15, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1f, 0x64, 0x69, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_server_service_v1_host_proto_rawDescOnce sync.Once
	file_api_server_service_v1_host_proto_rawDescData = file_api_server_service_v1_host_proto_rawDesc
)

func file_api_server_service_v1_host_proto_rawDescGZIP() []byte {
	file_api_server_service_v1_host_proto_rawDescOnce.Do(func() {
		file_api_server_service_v1_host_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_server_service_v1_host_proto_rawDescData)
	})
	return file_api_server_service_v1_host_proto_rawDescData
}

var file_api_server_service_v1_host_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_server_service_v1_host_proto_goTypes = []interface{}{
	(*HostInfo)(nil),                 // 0: api.server.service.v1.HostInfo
	(*CreateHostReq)(nil),            // 1: api.server.service.v1.CreateHostReq
	(*CreateHostReply)(nil),          // 2: api.server.service.v1.CreateHostReply
	(*ListHostReq)(nil),              // 3: api.server.service.v1.ListHostReq
	(*ListHostReply)(nil),            // 4: api.server.service.v1.ListHostReply
	(*GetHostByVerifyCodeReq)(nil),   // 5: api.server.service.v1.GetHostByVerifyCodeReq
	(*GetHostByVerifyCodeReply)(nil), // 6: api.server.service.v1.GetHostByVerifyCodeReply
	(*AuthHostReq)(nil),              // 7: api.server.service.v1.AuthHostReq
	(*AuthHostReply)(nil),            // 8: api.server.service.v1.AuthHostReply
}
var file_api_server_service_v1_host_proto_depIdxs = []int32{
	0, // 0: api.server.service.v1.CreateHostReply.data:type_name -> api.server.service.v1.HostInfo
	0, // 1: api.server.service.v1.ListHostReply.data:type_name -> api.server.service.v1.HostInfo
	0, // 2: api.server.service.v1.GetHostByVerifyCodeReply.host:type_name -> api.server.service.v1.HostInfo
	1, // 3: api.server.service.v1.Host.CreateHost:input_type -> api.server.service.v1.CreateHostReq
	3, // 4: api.server.service.v1.Host.ListHost:input_type -> api.server.service.v1.ListHostReq
	5, // 5: api.server.service.v1.Host.GetHostByVerifyCode:input_type -> api.server.service.v1.GetHostByVerifyCodeReq
	7, // 6: api.server.service.v1.Host.AuthHost:input_type -> api.server.service.v1.AuthHostReq
	2, // 7: api.server.service.v1.Host.CreateHost:output_type -> api.server.service.v1.CreateHostReply
	4, // 8: api.server.service.v1.Host.ListHost:output_type -> api.server.service.v1.ListHostReply
	6, // 9: api.server.service.v1.Host.GetHostByVerifyCode:output_type -> api.server.service.v1.GetHostByVerifyCodeReply
	8, // 10: api.server.service.v1.Host.AuthHost:output_type -> api.server.service.v1.AuthHostReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_server_service_v1_host_proto_init() }
func file_api_server_service_v1_host_proto_init() {
	if File_api_server_service_v1_host_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_server_service_v1_host_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_service_v1_host_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_service_v1_host_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_service_v1_host_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_service_v1_host_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_service_v1_host_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostByVerifyCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_service_v1_host_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostByVerifyCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_service_v1_host_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthHostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_service_v1_host_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthHostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_server_service_v1_host_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_server_service_v1_host_proto_goTypes,
		DependencyIndexes: file_api_server_service_v1_host_proto_depIdxs,
		MessageInfos:      file_api_server_service_v1_host_proto_msgTypes,
	}.Build()
	File_api_server_service_v1_host_proto = out.File
	file_api_server_service_v1_host_proto_rawDesc = nil
	file_api_server_service_v1_host_proto_goTypes = nil
	file_api_server_service_v1_host_proto_depIdxs = nil
}
