trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8200
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9200
    timeout: 1s
  tls:
    caCertFile: app/server/service/configs/ca.pem
    certFile: app/server/service/configs/cert.pem
    keyFile: app/server/service/configs/cert.key
data:
  database:
    driver: sqlite3
    source: file:app/server/service/server.db?&_fk=1