// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/client/service/v1/client.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListNetReq) Reset() {
	*x = ListNetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetReq) ProtoMessage() {}

func (x *ListNetReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetReq.ProtoReflect.Descriptor instead.
func (*ListNetReq) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{0}
}

type ListNetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*ListNetReply_Net `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListNetReply) Reset() {
	*x = ListNetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetReply) ProtoMessage() {}

func (x *ListNetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetReply.ProtoReflect.Descriptor instead.
func (*ListNetReply) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *ListNetReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListNetReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListNetReply) GetData() []*ListNetReply_Net {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListComReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListComReq) Reset() {
	*x = ListComReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListComReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComReq) ProtoMessage() {}

func (x *ListComReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComReq.ProtoReflect.Descriptor instead.
func (*ListComReq) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{2}
}

type ListComReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*ListComReply_Com `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListComReply) Reset() {
	*x = ListComReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListComReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComReply) ProtoMessage() {}

func (x *ListComReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComReply.ProtoReflect.Descriptor instead.
func (*ListComReply) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{3}
}

func (x *ListComReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListComReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListComReply) GetData() []*ListComReply_Com {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSystemInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSystemInfoReq) Reset() {
	*x = GetSystemInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoReq) ProtoMessage() {}

func (x *GetSystemInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoReq.ProtoReflect.Descriptor instead.
func (*GetSystemInfoReq) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{4}
}

type GetSystemInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *GetSystemInfoReply_SystemInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetSystemInfoReply) Reset() {
	*x = GetSystemInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoReply) ProtoMessage() {}

func (x *GetSystemInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoReply.ProtoReflect.Descriptor instead.
func (*GetSystemInfoReply) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{5}
}

func (x *GetSystemInfoReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSystemInfoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetSystemInfoReply) GetData() *GetSystemInfoReply_SystemInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListAntivirusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAntivirusReq) Reset() {
	*x = ListAntivirusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAntivirusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAntivirusReq) ProtoMessage() {}

func (x *ListAntivirusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAntivirusReq.ProtoReflect.Descriptor instead.
func (*ListAntivirusReq) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{6}
}

type ListAntivirusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListAntivirusReply) Reset() {
	*x = ListAntivirusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAntivirusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAntivirusReply) ProtoMessage() {}

func (x *ListAntivirusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAntivirusReply.ProtoReflect.Descriptor instead.
func (*ListAntivirusReply) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{7}
}

func (x *ListAntivirusReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListAntivirusReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListAntivirusReply) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetHostInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHostInfoReq) Reset() {
	*x = GetHostInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoReq) ProtoMessage() {}

func (x *GetHostInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoReq.ProtoReflect.Descriptor instead.
func (*GetHostInfoReq) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{8}
}

type GetHostInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *GetHostInfoReply_HostInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetHostInfoReply) Reset() {
	*x = GetHostInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoReply) ProtoMessage() {}

func (x *GetHostInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoReply.ProtoReflect.Descriptor instead.
func (*GetHostInfoReply) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{9}
}

func (x *GetHostInfoReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetHostInfoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetHostInfoReply) GetData() *GetHostInfoReply_HostInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckFirstConnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckFirstConnReq) Reset() {
	*x = CheckFirstConnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFirstConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFirstConnReq) ProtoMessage() {}

func (x *CheckFirstConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFirstConnReq.ProtoReflect.Descriptor instead.
func (*CheckFirstConnReq) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{10}
}

type CheckFirstConnReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *CheckFirstConnReply_ConnCheck `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CheckFirstConnReply) Reset() {
	*x = CheckFirstConnReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFirstConnReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFirstConnReply) ProtoMessage() {}

func (x *CheckFirstConnReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFirstConnReply.ProtoReflect.Descriptor instead.
func (*CheckFirstConnReply) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{11}
}

func (x *CheckFirstConnReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckFirstConnReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CheckFirstConnReply) GetData() *CheckFirstConnReply_ConnCheck {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConnectServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectServerReq) Reset() {
	*x = ConnectServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectServerReq) ProtoMessage() {}

func (x *ConnectServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectServerReq.ProtoReflect.Descriptor instead.
func (*ConnectServerReq) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{12}
}

type ConnectServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ConnectServerReply) Reset() {
	*x = ConnectServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectServerReply) ProtoMessage() {}

func (x *ConnectServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectServerReply.ProtoReflect.Descriptor instead.
func (*ConnectServerReply) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{13}
}

func (x *ConnectServerReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConnectServerReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ListNetReply_Net struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip         string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Gateway    string `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	SubnetMask string `protobuf:"bytes,4,opt,name=subnet_mask,json=subnetMask,proto3" json:"subnet_mask,omitempty"`
	Mac        string `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (x *ListNetReply_Net) Reset() {
	*x = ListNetReply_Net{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNetReply_Net) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetReply_Net) ProtoMessage() {}

func (x *ListNetReply_Net) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetReply_Net.ProtoReflect.Descriptor instead.
func (*ListNetReply_Net) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListNetReply_Net) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListNetReply_Net) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ListNetReply_Net) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *ListNetReply_Net) GetSubnetMask() string {
	if x != nil {
		return x.SubnetMask
	}
	return ""
}

func (x *ListNetReply_Net) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type ListComReply_Com struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *ListComReply_Com) Reset() {
	*x = ListComReply_Com{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListComReply_Com) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComReply_Com) ProtoMessage() {}

func (x *ListComReply_Com) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComReply_Com.ProtoReflect.Descriptor instead.
func (*ListComReply_Com) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListComReply_Com) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListComReply_Com) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type GetSystemInfoReply_SystemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Os      string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetSystemInfoReply_SystemInfo) Reset() {
	*x = GetSystemInfoReply_SystemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemInfoReply_SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoReply_SystemInfo) ProtoMessage() {}

func (x *GetSystemInfoReply_SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoReply_SystemInfo.ProtoReflect.Descriptor instead.
func (*GetSystemInfoReply_SystemInfo) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetSystemInfoReply_SystemInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSystemInfoReply_SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetSystemInfoReply_SystemInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetHostInfoReply_HostInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Manager string `protobuf:"bytes,2,opt,name=manager,proto3" json:"manager,omitempty"`
	Phone   string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *GetHostInfoReply_HostInfo) Reset() {
	*x = GetHostInfoReply_HostInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHostInfoReply_HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoReply_HostInfo) ProtoMessage() {}

func (x *GetHostInfoReply_HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoReply_HostInfo.ProtoReflect.Descriptor instead.
func (*GetHostInfoReply_HostInfo) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetHostInfoReply_HostInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHostInfoReply_HostInfo) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *GetHostInfoReply_HostInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CheckFirstConnReply_ConnCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First      bool   `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	VerifyCode string `protobuf:"bytes,2,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
}

func (x *CheckFirstConnReply_ConnCheck) Reset() {
	*x = CheckFirstConnReply_ConnCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_client_service_v1_client_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFirstConnReply_ConnCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFirstConnReply_ConnCheck) ProtoMessage() {}

func (x *CheckFirstConnReply_ConnCheck) ProtoReflect() protoreflect.Message {
	mi := &file_api_client_service_v1_client_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFirstConnReply_ConnCheck.ProtoReflect.Descriptor instead.
func (*CheckFirstConnReply_ConnCheck) Descriptor() ([]byte, []int) {
	return file_api_client_service_v1_client_proto_rawDescGZIP(), []int{11, 0}
}

func (x *CheckFirstConnReply_ConnCheck) GetFirst() bool {
	if x != nil {
		return x.First
	}
	return false
}

func (x *CheckFirstConnReply_ConnCheck) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

var File_api_client_service_v1_client_proto protoreflect.FileDescriptor

var file_api_client_service_v1_client_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x4c, 0x69, 0x73,
	0x74, 0x4e, 0x65, 0x74, 0x52, 0x65, 0x71, 0x22, 0xe9, 0x01, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x4e, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x3b,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x4e, 0x65, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x76, 0x0a, 0x03, 0x4e,
	0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x4d, 0x61, 0x73,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x61, 0x63, 0x22, 0x0c, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x22, 0xa0, 0x01, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2d, 0x0a, 0x03, 0x43, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0xd0, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x48, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x4a, 0x0a, 0x0a, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6e, 0x74, 0x69, 0x76, 0x69, 0x72, 0x75, 0x73, 0x52, 0x65, 0x71, 0x22,
	0x4e, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x74, 0x69, 0x76, 0x69, 0x72, 0x75, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x22, 0xce, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x44, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x4e, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x22, 0xc8, 0x01, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x48, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x41, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x3a, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0x81, 0x07, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x6e, 0x0a,
	0x07, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x12, 0x6e, 0x0a,
	0x07, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x12, 0x81, 0x01,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x2f, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x86, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x74, 0x69, 0x76, 0x69,
	0x72, 0x75, 0x73, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x6e, 0x74, 0x69, 0x76, 0x69, 0x72, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x74, 0x69, 0x76, 0x69, 0x72,
	0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x12,
	0x19, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73,
	0x2f, 0x61, 0x6e, 0x74, 0x69, 0x76, 0x69, 0x72, 0x75, 0x73, 0x12, 0x7c, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x17, 0x12, 0x15, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68,
	0x6f, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x86, 0x01, 0x0a, 0x0e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x28, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x46, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x2f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x12, 0x82, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12,
	0x15, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e,
	0x6e, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x42, 0x3b, 0x0a, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x60, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x1f, 0x64, 0x69, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_client_service_v1_client_proto_rawDescOnce sync.Once
	file_api_client_service_v1_client_proto_rawDescData = file_api_client_service_v1_client_proto_rawDesc
)

func file_api_client_service_v1_client_proto_rawDescGZIP() []byte {
	file_api_client_service_v1_client_proto_rawDescOnce.Do(func() {
		file_api_client_service_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_client_service_v1_client_proto_rawDescData)
	})
	return file_api_client_service_v1_client_proto_rawDescData
}

var file_api_client_service_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_client_service_v1_client_proto_goTypes = []interface{}{
	(*ListNetReq)(nil),                    // 0: api.client.service.v1.ListNetReq
	(*ListNetReply)(nil),                  // 1: api.client.service.v1.ListNetReply
	(*ListComReq)(nil),                    // 2: api.client.service.v1.ListComReq
	(*ListComReply)(nil),                  // 3: api.client.service.v1.ListComReply
	(*GetSystemInfoReq)(nil),              // 4: api.client.service.v1.GetSystemInfoReq
	(*GetSystemInfoReply)(nil),            // 5: api.client.service.v1.GetSystemInfoReply
	(*ListAntivirusReq)(nil),              // 6: api.client.service.v1.ListAntivirusReq
	(*ListAntivirusReply)(nil),            // 7: api.client.service.v1.ListAntivirusReply
	(*GetHostInfoReq)(nil),                // 8: api.client.service.v1.GetHostInfoReq
	(*GetHostInfoReply)(nil),              // 9: api.client.service.v1.GetHostInfoReply
	(*CheckFirstConnReq)(nil),             // 10: api.client.service.v1.CheckFirstConnReq
	(*CheckFirstConnReply)(nil),           // 11: api.client.service.v1.CheckFirstConnReply
	(*ConnectServerReq)(nil),              // 12: api.client.service.v1.ConnectServerReq
	(*ConnectServerReply)(nil),            // 13: api.client.service.v1.ConnectServerReply
	(*ListNetReply_Net)(nil),              // 14: api.client.service.v1.ListNetReply.Net
	(*ListComReply_Com)(nil),              // 15: api.client.service.v1.ListComReply.Com
	(*GetSystemInfoReply_SystemInfo)(nil), // 16: api.client.service.v1.GetSystemInfoReply.SystemInfo
	(*GetHostInfoReply_HostInfo)(nil),     // 17: api.client.service.v1.GetHostInfoReply.HostInfo
	(*CheckFirstConnReply_ConnCheck)(nil), // 18: api.client.service.v1.CheckFirstConnReply.ConnCheck
}
var file_api_client_service_v1_client_proto_depIdxs = []int32{
	14, // 0: api.client.service.v1.ListNetReply.data:type_name -> api.client.service.v1.ListNetReply.Net
	15, // 1: api.client.service.v1.ListComReply.data:type_name -> api.client.service.v1.ListComReply.Com
	16, // 2: api.client.service.v1.GetSystemInfoReply.data:type_name -> api.client.service.v1.GetSystemInfoReply.SystemInfo
	17, // 3: api.client.service.v1.GetHostInfoReply.data:type_name -> api.client.service.v1.GetHostInfoReply.HostInfo
	18, // 4: api.client.service.v1.CheckFirstConnReply.data:type_name -> api.client.service.v1.CheckFirstConnReply.ConnCheck
	0,  // 5: api.client.service.v1.Client.ListNet:input_type -> api.client.service.v1.ListNetReq
	2,  // 6: api.client.service.v1.Client.ListCom:input_type -> api.client.service.v1.ListComReq
	4,  // 7: api.client.service.v1.Client.GetSystemInfo:input_type -> api.client.service.v1.GetSystemInfoReq
	6,  // 8: api.client.service.v1.Client.ListAntivirus:input_type -> api.client.service.v1.ListAntivirusReq
	8,  // 9: api.client.service.v1.Client.GetHostInfo:input_type -> api.client.service.v1.GetHostInfoReq
	10, // 10: api.client.service.v1.Client.CheckFirstConn:input_type -> api.client.service.v1.CheckFirstConnReq
	12, // 11: api.client.service.v1.Client.ConnectServer:input_type -> api.client.service.v1.ConnectServerReq
	1,  // 12: api.client.service.v1.Client.ListNet:output_type -> api.client.service.v1.ListNetReply
	3,  // 13: api.client.service.v1.Client.ListCom:output_type -> api.client.service.v1.ListComReply
	5,  // 14: api.client.service.v1.Client.GetSystemInfo:output_type -> api.client.service.v1.GetSystemInfoReply
	7,  // 15: api.client.service.v1.Client.ListAntivirus:output_type -> api.client.service.v1.ListAntivirusReply
	9,  // 16: api.client.service.v1.Client.GetHostInfo:output_type -> api.client.service.v1.GetHostInfoReply
	11, // 17: api.client.service.v1.Client.CheckFirstConn:output_type -> api.client.service.v1.CheckFirstConnReply
	13, // 18: api.client.service.v1.Client.ConnectServer:output_type -> api.client.service.v1.ConnectServerReply
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_client_service_v1_client_proto_init() }
func file_api_client_service_v1_client_proto_init() {
	if File_api_client_service_v1_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_client_service_v1_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListComReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListComReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAntivirusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAntivirusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFirstConnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFirstConnReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNetReply_Net); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListComReply_Com); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemInfoReply_SystemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHostInfoReply_HostInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_client_service_v1_client_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFirstConnReply_ConnCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_client_service_v1_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_client_service_v1_client_proto_goTypes,
		DependencyIndexes: file_api_client_service_v1_client_proto_depIdxs,
		MessageInfos:      file_api_client_service_v1_client_proto_msgTypes,
	}.Build()
	File_api_client_service_v1_client_proto = out.File
	file_api_client_service_v1_client_proto_rawDesc = nil
	file_api_client_service_v1_client_proto_goTypes = nil
	file_api_client_service_v1_client_proto_depIdxs = nil
}
